#!/usr/bin/env php
<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
if (PHP_SAPI !== 'cli') {
    echo 'bin must be run as a CLI application';
    exit(1);
}

//define program file name
define( 'PROG_FILE', __FILE__ );
define( 'PROG_NAME', basename( PROG_FILE ) );
define( 'BP', __DIR__ );
 
//include files
include __DIR__ . "/vendor/autoload.php";
include __DIR__ . "/app/config.php";
include __DIR__ . "/app/Helper.php";

try {
    //$handler = new \Magento\Framework\App\ErrorHandler();
    //set_error_handler([$handler, 'handler']);

    $application = new Symfony\Component\Console\Application('Tit CLI', '1.0.0');
	
	//other commands
	//object name => command name
	$commands = \Config::get('commands');
	if(is_array($commands)){
		foreach($commands as $class => $cmd_name){
			$application->add(new $class($cmd_name));
		}
	}
		
	//set commands
	$commandList = new Symfony\Component\Console\Command\ListCommand();
	$application->add($commandList);
	
	//run application
    $application->run();
	
} catch (\Exception $e) {
    while ($e) {
        echo $e->getMessage();
        echo $e->getTraceAsString();
        echo "\n\n";
        $e = $e->getPrevious();
    }
}

